### ISSUE TITLE
attemptNo in function checkIfLockedOut() does not exist in the table with no code to insert values to it either

### ISSUE THREAD

**Issue by adesignguy** [Sledro/PHP-Login#2]
There is no code to insert attemptNo either, you can fix it by adjusting the function as below.

You'll always be locked out as the function is looking for 4 columns in the table when there is only three. So you need to adjust the array. I also found some other issues that I have fixed, its probably not a good idea to use this code unless you know what you are doing - it's good code but it's not quite complete -  it's also best to log to the database rather than to a file, but it's also never really a good idea to try/catch every database statement either.

On the forgotten password request page, I modified it to send the token to the users email address if it exists rather than display it and also show a generic message stating "If this email address exists, you'll receive a reset link to your registered email address". It just makes more sense to do that for security.

`function checkIfLockedOut($uid, $conn) {
        try{
            $stmt = $conn->prepare("SELECT time FROM login_attempts WHERE uid=:uid ORDER BY time DESC LIMIT 5");
            $stmt->bindParam(':uid', $uid);
            $stmt->execute();
            $result = $stmt->fetchAll();
        }catch(PDOException $exception){ 
         //   logme($uid,time(),"PDOException","SELECT attemptNo FROM login_attempts WHERE uid=:uid","Error", $exception, "n/a");
        }
     
     
     //if($result[4][0]!=""){                         //was array [4] but attemptNo above doesn't actually exist.
        //$answer=$result[0][0]-$result[4][0];
        
        if($result[3][0]!=""){
        $answer=$result[0][0]-$result[3][0];
     
        if($answer < 300){
            return 1;
        }else{
            return 0;
        }
    }else{
        return 0;
    }
} `

**Comment by sledro** [comment]
Hey @adesignguy 

Thanks for checking out the code.

1 - Its been a few years since I've looked at this code but as far as I can remember - The system is designed to lock the user out if they attempt to login 5 or more times within 5 minutes. This means there is no need for **attemptNo** as its time-based. We can see how many times the user attempted to login by counting the rows in the log (this is what `$result[4][0]` is, first 4 rows not columns).

The query in the below code is just a log message that probably should be renamed:

`logme($uid,time(),"PDOException","SELECT attemptNo FROM login_attempts WHERE uid=:uid","Error", $exception, "n/a");`

2 - The data was logged to an encrypted log file as it was part of the specification of this assignment. Once the file is encrypted I don't see any issue with storing the log to a file as most systems do. It useful if your database goes down or has any issues. See [here](https://stackoverflow.com/questions/7257242/whats-more-efficient-storing-logs-in-sql-database-or-files#:~:text=I%20think%20storing%20logs%20in,more%20time%20for%20database%20maintainence.)

3 - I agree with you about emailing the user the password reset. Again this was part of our specification for this assignment as it made more sense for the professor to correct. If you want to make a PR id be glad to include this in the code.

**Comment by adesignguy** [comment]
Hi thanks for the fast reply and for sharing your code, I'll take another proper look tomorrow, You're right, but should this not allowing more than five login attempts per user entered into the database? If the list becomes larger than 5, then it seems it never lets you back in. 

Unless something is wrong with my setup, I'm getting every attempt logged into the database, even after being locked out (I'm assuming you were trying to lock more attempts out for a further 5 minutes if they keep trying?)
 
E.g. Reverting the code back, If had about 40 entries in the login_attempts table from testing, it will work after deleting the previous 35 attempts to show the last 5.  That's what is wrong - it just wont let me in unless I do that.
